---
applications:
- name: APPNAME
  memory: 256M
  instances: 1
  command: node app.js
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  env:
    DT_NODE_ID: APPNAME
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NAME=Production DEPLOYMENT_COLOR=APPCOLOR
    BUILD_NUMBER: 1
    DEPLOYMENT_GRP_NAME: Production
    DUMMY_VAR: changethis

